apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-develop
  namespace: openshift-gitops
  labels:
    app: node-build-config-openshift
    environment: dev
spec:
  destination:
    namespace: demo-develop
    server: https://kubernetes.default.svc
  project: demo-dev
  source:
    kustomize:
    path: cd-sample/deploy/overlays/dev
    repoURL: http://<GITEA_HOSTNAME>/gitea/cd-sample.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true 
      - CreateNamespace=true
