apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-production
  namespace: openshift-gitops
  labels:
    app: node-build-config-openshift
    environment: prod
spec:
  destination:
    namespace: demo-production
    server: https://kubernetes.default.svc
  project: demo-prod
  source:
    kustomize:
    repoURL: http://<GITEA_HOSTNAME>/gitea/cd-sample.git
    path: deploy/overlays/prod
    targetRevision: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true 
      - CreateNamespace=true
