apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-staging
  namespace: openshift-gitops
  labels:
    app: node-build-config-openshift
    environment: stg
spec:
  destination:
    namespace: demo-staging
    server: https://kubernetes.default.svc
  project: demo-stg
  source:
    kustomize:
    repoURL: http://<GITEA_HOSTNAME>/gitea/cd-sample.git
    path: deploy/overlays/stg
    targetRevision: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true 
      - CreateNamespace=true
